import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib"

    public const val asm: String = "org.ow2.asm:asm:_"

    public const val asm_commons: String = "org.ow2.asm:asm-commons:_"

    public const val asm_tree: String = "org.ow2.asm:asm-tree:_"

    public const val asm_util: String = "org.ow2.asm:asm-util:_"
}
